### ISSUE TITLE
Error after activating the CAS Module

### ISSUE THREAD

**Issue by PeziBuu** [fnp/piwik-CASLogin#1]
Hey there,

I'm using Piwik 2.7 and need the CAS Login module. After activating, I get directed to an error page. Piwik can't open a session. Before the update, everyting was fine. I had the Version 1.9. 
The recommendation from the error page is to set the following permissions which I did:
chown -R www-data:www-data /var/www/piwik/tmp/sessions/
chmod -R 0755 /var/www/piwik/tmp/sessions/

Nothing changed. Another option was, to enable database session storage. This don't work either. 

Does anybody else has this issue or knows a solution? Thanks in advance.

Here the debug message:
Debug: the original error was 
session has already been started by session.auto-start or session_start()

Peter

**Comment by ludopaquet** [comment]
Hi,

same problem here, need to change in Client.php session_start by try {
    Zend_Session::start();
} catch(Zend_Session_Exception $e) {
    session_start();
}

**Comment by rczajka** [comment]
I believe the double-session-start problem is something I've fixed in 4443d60bb1b3c12b04c14f45e1541a64b1e31e6d. Is it still happening?

**Comment by rczajka** [comment]
Looks like I was wrong. Can you test with b11e7f8e5f31437c8a2e1071ad0035af94ff1053?

**Comment by ludopaquet** [comment]
Works better with b11e7f8 ! Thanks rczajka !
